import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { join } from 'node:path';
import { ROOT, COLLECTION, PREVIEW, expectedPrototype, syncPrototype, annotatePreviewApp } from '../scripts/sync-prototype.mjs';
import * as rootStorage from '../src/storage.js';
import * as previewStorage from '../docs/design_refs/answer-lens/src/storage.js';
import { demoSession } from '../src/demo.js';
import { beginBlind } from '../src/core.js';
import { legacySession } from './fixtures/sessions.mjs';
const read = path => readFile(join(ROOT, COLLECTION, path), 'utf8');
const digest = text => createHash('sha256').update(text).digest('hex');
class MemoryStorage {
  data = new Map(); calls = [];
  getItem(key) { this.calls.push(['get', key]); return this.data.get(key) ?? null; }
  setItem(key, value) { this.calls.push(['set', key]); this.data.set(key, value); }
  removeItem(key) { this.calls.push(['remove', key]); this.data.delete(key); }
  clear() { assert.fail('Origin-wide deletion is forbidden'); }
}
function seed() {
  const storage = new MemoryStorage();
  storage.data.set(rootStorage.STORAGE_KEY, JSON.stringify(beginBlind(demoSession(true), { seed: 13, now: '2026-09-21T07:00:00.000Z' })));
  storage.data.set(rootStorage.LEGACY_KEY, JSON.stringify({ ...legacySession(), remember: true }));
  return storage;
}
test('current navigable prototype is reproducible and its check is read-only', async () => {
  const a = await expectedPrototype(); const b = await expectedPrototype();
  assert.deepEqual(a, b);
  for (const [path, text] of a) assert.equal(await read(path), text, path);
  assert.deepEqual(await syncPrototype(), { checked: 13, updated: [], mode: 'check' });
});
test('collection preserves existing IDs and declares supported desktop and smartphone journeys', async () => {
  const m = JSON.parse(await read('prancheta.json'));
  assert.equal(m.versao, 1); assert.equal(m.colecao.finalidade, 'atual');
  assert.equal(m.colecao.inicio, 'comparison.html'); assert.equal(m.telas['comparison.html'].idTela, 'answer-lens:comparison');
  assert.equal(m.colecao.jornadas.find(j => j.id === 'compare').inicio, 'comparison.html');
  assert.deepEqual(m.telas['comparison.html'].viewport, { largura: 1440, altura: 1000 });
  assert.deepEqual(m.telas['mobile.html'].viewport, { largura: 390, altura: 844 });
  assert.equal(m.colecao.jornadas.find(j => j.id === 'compare-mobile').dispositivo, 'smartphone');
  assert.equal(m.colecao.versaoDoProduto, '2.0.0');
  for (const screen of Object.values(m.telas)) {
    assert.equal(screen.build, '2.0.0'); assert.equal(screen.capacidade, 'interacao-local');
    assert.ok(screen.recursos.includes('src/output.js'));
    for (const path of screen.recursos) { assert.ok(!path.includes('..')); assert.ok((await read(path)).length); }
  }
});
test('local resource manifest binds the actual root and generated bytes', async () => {
  const m = JSON.parse(await read('resources.json'));
  for (const [path, sha] of Object.entries(m.sourceHashes)) assert.equal(digest(await readFile(join(ROOT, path), 'utf8')), sha, path);
  for (const [path, sha] of Object.entries(m.generatedHashes)) assert.equal(digest(await read(path)), sha, path);
  assert.deepEqual(m.isolation, PREVIEW);
  for (const path of ['styles.css', 'icon.svg', 'src/core.js', 'src/demo.js', 'src/output.js']) assert.equal(await read(path), await readFile(join(ROOT, path), 'utf8'));
  assert.equal(await read('src/app.js'), annotatePreviewApp(await readFile(join(ROOT, 'src/app.js'), 'utf8')));
});
test('all existing and new HTML entries run v2 with a truthful isolation notice and save-status elements', async () => {
  for (const path of ['index.html', 'comparison.html', 'mobile.html']) {
    const html = await read(path);
    assert.match(html, /Isolated preview/); assert.match(html, /id="data-status"/); assert.match(html, /id="save-retry"/);
    assert.match(html, /type="module" src="\.\/src\/app.js"/);
    assert.doesNotMatch(html, /(?:src|href)="(?:https?:)?\/\//);
  }
});
test('preview storage, legacy migration and Web Lock names are distinct from the real application', () => {
  assert.equal(previewStorage.STORAGE_KEY, PREVIEW.storageKey);
  assert.equal(previewStorage.LEGACY_KEY, PREVIEW.legacyKey);
  assert.equal(previewStorage.LOCK_NAME, PREVIEW.lockName);
  for (const key of ['STORAGE_KEY', 'LEGACY_KEY', 'LOCK_NAME']) assert.notEqual(previewStorage[key], rootStorage[key]);
});
test('opening, saving, opting out and resetting preview never reads or modifies real-app keys', () => {
  const storage = seed(); const before = new Map(storage.data);
  assert.equal(previewStorage.loadLocal(() => storage).session, null);
  assert.equal(previewStorage.loadLegacy(() => storage).session, null);
  assert.equal(previewStorage.saveLocal(demoSession(true), () => storage, null).ok, true);
  assert.equal(previewStorage.loadLocal(() => storage).session.synthetic, true);
  assert.equal(previewStorage.clearLocal(() => storage).ok, true);
  assert.deepEqual(storage.data, before);
  assert.ok(storage.calls.every(([, key]) => key === PREVIEW.storageKey || key === PREVIEW.legacyKey));
});
test('preview legacy import is explicit, local to the preview and leaves both legacy records untouched', () => {
  const storage = seed(); const before = new Map(storage.data); const legacy = JSON.stringify({ ...legacySession(), remember: true });
  storage.data.set(PREVIEW.legacyKey, legacy);
  const result = previewStorage.loadLegacy(() => storage);
  assert.equal(result.ok, true); assert.equal(result.session.version, 2); assert.equal(result.session.remember, false);
  result.session.remember = true; assert.equal(previewStorage.saveLocal(result.session, () => storage, null).ok, true);
  for (const [key, value] of before) assert.equal(storage.data.get(key), value);
  assert.equal(storage.data.get(PREVIEW.legacyKey), legacy);
  assert.ok(storage.calls.every(([, key]) => key === PREVIEW.storageKey || key === PREVIEW.legacyKey));
});
test('preview offline shell includes every HTML entry and uses its own cache namespace', async () => {
  const sw = await read('sw.js');
  assert.match(sw, /answer-lens-preview-shell:/); assert.match(sw, /catalog-r3/);
  for (const entry of ['index.html', 'comparison.html', 'mobile.html', 'src/output.js']) assert.ok(sw.includes(`'./${entry}'`));
  assert.doesNotMatch(sw, /answer-lens-shell:|localStorage|\.clear\(/);
});
